MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    NUM_CLASSES: 81
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  #  STEPS: (60000, 80000)
  #  MAX_ITER: 90000

  #  LR_POLICY: steps_with_decay
  #  BASE_LR: 0.02
  GAMMA: 0.1
  MAX_ITER: 7500
  STEPS: [0, 3750, 5000]
  # Equivalent schedules with...
  # 1 GPU:
  #   BASE_LR: 0.0025
  #   MAX_ITER: 60000
  #   STEPS: [0, 30000, 40000]
  # 2 GPUs:
  #   BASE_LR: 0.005
  #   MAX_ITER: 30000
  #   STEPS: [0, 15000, 20000]
  # 4 GPUs:
  #   BASE_LR: 0.01
  #   MAX_ITER: 15000
  #   STEPS: [0, 7500, 10000]
  # 8 GPUs:
  #   BASE_LR: 0.02
  #   MAX_ITER: 7500
  #   STEPS: [0, 3750, 5000]

  #FPN:
  #  FPN_ON: True
  #  MULTILEVEL_ROIS: True
  #  MULTILEVEL_RPN: True
  #FAST_RCNN:
  #  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  #  ROI_XFORM_METHOD: RoIAlign
  #  ROI_XFORM_RESOLUTION: 7
  #  ROI_XFORM_SAMPLING_RATIO: 2
  #TRAIN:
  #  #WEIGHTS: https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  #  SCALES: (500,)
  #  MAX_SIZE: 833
  #  BATCH_SIZE_PER_IM: 256
  #  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  #TEST:
  #  SCALE: 500
  #  MAX_SIZE: 833
  #  NMS: 0.5
  #  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  #  RPN_POST_NMS_TOP_N: 1000
#OUTPUT_DIR: .
